project_name: gitlab-download-release

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: gitlab-download-release
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    goarm:
      - v8

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: checksums.txt

changelog:
  use: github
